class MenuMakanan {
  final int id;
  final List<String>? image;
  final String namaMakanan, lokasi, bahan, alat, caraMasak, review;
  final double rateReview;

  MenuMakanan({
    required this.id,
    required this.namaMakanan,
    required this.image,
    required this.lokasi,
    required this.bahan,
    required this.alat,
    required this.caraMasak,
    required this.review,
    required this.rateReview,
  });
}

List<MenuMakanan> menuMakananList = [
  MenuMakanan(
    id: 1,
    namaMakanan: 'Laksa Cianjur',
    image: ['https://i.pinimg.com/736x/06/6c/be/066cbe29fe7a0ab02c5db22f0b05bdd7.jpg'],
    lokasi: 'Cianjur',
    bahan: 'Mie kuning, santan, oncom, tauge, daun bawang, seledri.',
    alat: 'Panci, sendok, mangkok.',
    caraMasak: 'Masak santan dengan bumbu, tambahkan mie dan topping, sajikan.',
    review: 'Laksa yang sangat gurih dengan rasa khas dari oncom dan santannya.',
    rateReview: 4.5,
  ),
  MenuMakanan(
    id: 2,
    namaMakanan: 'Manisan Cianjur',
    image: ['https://i.pinimg.com/736x/ee/26/ec/ee26ecc86420d96b9abba2f25d430397.jpg'],
    lokasi: 'Cianjur',
    bahan: 'Buah mangga, gula pasir, air, garam.',
    alat: 'Pisau, toples, kompor.',
    caraMasak: 'Potong buah, rebus gula dan air, rendam buah dalam larutan gula.',
    review: 'Manisan segar dengan rasa manis dan sedikit asam, sangat menggoda.',
    rateReview: 4.7,
  ),
  MenuMakanan(
    id: 3,
    namaMakanan: 'Tauco Cianjur',
    image: ['https://i.pinimg.com/736x/06/9a/c3/069ac37fb5466f5777172f582ef1a198.jpg'],
    lokasi: 'Cianjur',
    bahan: 'Tauco, tempe, cabai, bawang merah, gula.',
    alat: 'Wajan, spatula, kompor.',
    caraMasak: 'Tumis bumbu, masukkan tauco dan tempe, masak hingga matang.',
    review: 'Rasa tauco yang kuat berpadu sempurna dengan gurihnya tempe.',
    rateReview: 4.4,
  ),
  MenuMakanan(
    id: 4,
    namaMakanan: 'Sate Maranggi Cianjur',
    image: ['https://i.pinimg.com/736x/d1/fb/1b/d1fb1b6bfdf84d580022f238700c3510.jpg'],
    lokasi: 'Cianjur',
    bahan: 'Daging sapi, kecap, bawang putih, jahe, merica.',
    alat: 'Tusuk sate, panggangan.',
    caraMasak: 'Rendam daging dengan bumbu, tusuk, panggang hingga matang.',
    review: 'Daging empuk dan bumbu meresap, cita rasa khas Cianjur.',
    rateReview: 4.8,
  ),
  MenuMakanan(
    id: 5,
    namaMakanan: 'Asinan Betawi Cianjur',
    image: ['https://example.com/asinan_cianjur.jpg'],
    lokasi: 'Cianjur',
    bahan: 'Sayuran segar, cuka, gula merah, cabai.',
    alat: 'Mangkuk, sendok.',
    caraMasak: 'Campur sayuran dengan kuah cuka pedas, sajikan dingin.',
    review: 'Rasa asam segar berpadu dengan pedas yang menggugah selera.',
    rateReview: 4.6,
  ),
  MenuMakanan(
    id: 6,
    namaMakanan: 'Peuyeum Cianjur',
    image: ['https://example.com/peuyeum_cianjur.jpg'],
    lokasi: 'Cianjur',
    bahan: 'Singkong, ragi tape.',
    alat: 'Kukusan, wadah fermentasi.',
    caraMasak: 'Rebus singkong, tambahkan ragi, fermentasikan beberapa hari.',
    review: 'Rasa manis alami dengan tekstur lembut yang khas.',
    rateReview: 4.9,
  ),
  MenuMakanan(
    id: 7,
    namaMakanan: 'Geco (Toge Tauco)',
    image: ['https://example.com/geco_cianjur.jpg'],
    lokasi: 'Cianjur',
    bahan: 'Tauge, tauco, mie kuning, tahu, bumbu kacang.',
    alat: 'Panci, sendok, piring.',
    caraMasak: 'Rebus tauge dan mie, tambahkan tauco dan bumbu kacang, sajikan.',
    review: 'Toge tauco yang sederhana namun kaya rasa.',
    rateReview: 4.6,
  ),
  MenuMakanan(
    id: 8,
    namaMakanan: 'Ayam Puyang Cianjur',
    image: ['https://example.com/ayam_puyang_cianjur.jpg'],
    lokasi: 'Cianjur',
    bahan: 'Ayam, santan, kunyit, daun jeruk.',
    alat: 'Wajan, kompor.',
    caraMasak: 'Masak ayam dengan santan dan bumbu hingga matang.',
    review: 'Rasa ayam yang gurih dengan rempah yang harum.',
    rateReview: 4.5,
  ),
  MenuMakanan(
    id: 9,
    namaMakanan: 'Bubur Ayam Cianjur',
    image: ['https://example.com/bubur_ayam_cianjur.jpg'],
    lokasi: 'Cianjur',
    bahan: 'Beras, ayam, bawang goreng, seledri.',
    alat: 'Panci, sendok, mangkok.',
    caraMasak: 'Masak bubur, tambahkan topping ayam dan bawang goreng.',
    review: 'Bubur lembut dengan rasa yang khas dan gurih.',
    rateReview: 4.7,
  ),
  MenuMakanan(
    id: 10,
    namaMakanan: 'Colenak Cianjur',
    image: ['https://example.com/colenak_cianjur.jpg'],
    lokasi: 'Cianjur',
    bahan: 'Peuyeum, gula merah, kelapa parut.',
    alat: 'Wajan, sendok.',
    caraMasak: 'Panggang peuyeum, tambahkan saus gula merah dan kelapa parut.',
    review: 'Kombinasi manis dan gurih yang sempurna.',
    rateReview: 4.8,
  ),
];
